### ISSUE TITLE
怎么样在本地计算机上怎么进行实验？

### ISSUE THREAD

**Issue by cnip** [CodeArtemis/TriggerRally#10]
请问：
1、用户最初的track数据是怎么产生的。
2、shared文件夹中的js文件通过怎么样的方式推送到前端，或者说，这个server和ui共享js的机制是怎样
3、coffee文件能不能都转成js吗，

**Comment by lambodriver2** [comment]
wright this in English!

**Comment by jareiko** [comment]
Via google translate:

# 

How to how to conduct experiments on the local computer?
I ask you:
1, the user first track data is generated.
2, Js files in the shared folder, how to push the front end, or rather, how the server and ui shared js mechanism
3, coffee files can all turn into js this

# 

I don't understand question 1, sorry. For questions 2 and 3:

The server can run in either development or production mode.

In development mode, files are served individually. CoffeeScript is compiled dynamically in the browser.

In production mode, you run `server/build/build.sh` to compile all the CS and JS into a single JS file.

# 

我不明白问题1，对不起。对于问题2和3：

该服务器可以运行在开发或生产模式。

在开发模式下，的文件单独供应。在浏览器中CoffeeScript的动态编译。

在生产模式下，运行服务器/建设/ build.sh编译所有的CS和JS成一个单一的JS文件。
