### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by Drvanon** [CodeArtemis/TriggerRally#17]
1. Another suggestion is a UI/ In the V1 replay you were able to see in replay how hard you drove enz. It would be really cool if there is just an UI wer you can see your speed.
2. Realistic coliisions would be nice to. on the moment the car feels like one piece of rock. It would be cool if there was put some realism to create a really nice effect.
3. Improved first person cam. I don't get the idea of sitting on the front of the car when you switch to first person. only an overlay in form of a ortho would be really nice.

This three thiks and the other suggestions will make this game perfect for me :dancer:  Let'shope it is realisable!

Succes. Hope I helped a little bit.

**Comment by jareiko** [comment]
1. An RPM/speed dial is coming very soon! Replay and time recording are in the pipeline but will take a bit longer.
2. A great idea but probably not going to happen in the near future. Car damage is a complex thing to simulate.
3. I will play with other options for the first person cam. Some people like the bonnet cam though...

PS. Thanks for numbering your suggestions, it makes it easier to respond to them. :)

**Comment by jareiko** [comment]
For (1) there is now an analog speedo. Digital to come later.

http://blog.triggerrally.com/post/40106915090/update-to-v3-released-analog-dials-for-rpm-and

**Comment by jareiko** [comment]
We now have digital speedo and a first person cam that doesn't show the car bonnet. Closing this issue.
