### ISSUE TITLE
One more suggestion + track editor fixes

### ISSUE THREAD

**Issue by copiousopioids** [CodeArtemis/TriggerRally#18]
I thought it would be helpful to add in the direction arrows marking the next checkpoint (Like in v1).

Love the editor, found it slow on my computer (But it's not super powerful) so maybe have some options to change rendering distance and quality.  I noticed that if you make a really long road that it will sometimes get very distorted at the starting point. Also the button to go to my personal profile is broken. Also some kind of menu to select a track you've made. Another thing: the strength definitely needs to be "stronger." I found that there were still large bumps in the road even with it on full power. Great overall however.

**Comment by jareiko** [comment]
Hmm, there seems to be some kind of database error when loading the recorded runs for your personal profile. I'll look into it, and in the meantime I've tweaked the code so you can at least still [view](http://triggerrally.com/user/Di6zVUjs) your created tracks and other info. It would be cool to be able to select tracks inside the editor too, maybe I will add that.

You can make the track almost perfectly smooth if you set all of the D values high. Does that help smooth out the bumps?

Thank you for the suggestions! :)

**Comment by jareiko** [comment]
Direction arrows are back in. I'll leave this issue open for quality options and the long roads problem.

http://blog.triggerrally.com/post/40106915090/update-to-v3-released-analog-dials-for-rpm-and

**Comment by jareiko** [comment]
Database error fixed by upgrading MongoDB from the ancient v1.4.4 to v2.2.2. Runs are visible on [your profile](http://triggerrally.com/user/Di6zVUjs) again.

**Comment by jareiko** [comment]
I think everything in this issue is fixed now, so closing the issue. Let me know if not.
