### ISSUE TITLE
Critical bug?

### ISSUE THREAD

**Issue by copiousopioids** [CodeArtemis/TriggerRally#21]
For some reason (and I've tried this on different days) I can edit all my tracks and stuff, but I cannot drive any of them. It will say "Trigger Rally--Loading" like normal, but then it will go black and the "3" of the countdown will show, but it will freeze like that. What happened? Seems that it cannot reach the texture files, but the editor can.
![jibiguvytdfgo](https://f.cloud.github.com/assets/2965376/41537/78543e50-55de-11e2-9f8e-5fef387d813f.png)

**Comment by jareiko** [comment]
Yikes, thanks for reporting that. I'd accidentally pushed the wrong code to the server. Should be fixed now. Please clear your browser cache, and if it's still not working let me know!

**Comment by copiousopioids** [comment]
Yep, works great! Thanks.
