### ISSUE TITLE
Conifer Texture Bug

### ISSUE THREAD

**Issue by copiousopioids** [CodeArtemis/TriggerRally#25]
I was having a problem where at high speeds the car would pass through trees, but I think you made the model more substantial and it fixed it. Now I bounce off trees :laughing: 

I noticed, however, that on the tree texture there is a little fleck that floats away from the rest of the tree by about the equivalent of 1.5 meters. You could probably just erase it real quick in the file, but it may be a bigger problem with tiling or some nonsense (hopefully not). I'll try to upload a screenshot later if you don't understand what I mean.

**Comment by jareiko** [comment]
Yeah, that fleck is because the trees are poorly modeled. Can you tell 3D modeling is not my specialty? ;)

I need to redo all the models soon so I will clean it up then.

**Comment by jareiko** [comment]
Oh and yes, the trees are more substantial from v3 onwards.

**Comment by jareiko** [comment]
Trees have now been completely replaced with a new model.
