### ISSUE TITLE
Splash text

### ISSUE THREAD

**Issue by ddorstijn** [CodeArtemis/TriggerRally#26]
LOLZ! Can't stop doing this :smile: 

Another really little enchentment:
- When you readch a checkpoint(see image)

Just to make you proud of what you have reached so far :+1: 
![trigger anno](https://f.cloud.github.com/assets/1730282/54434/2161fb50-5a93-11e2-8b8b-165de53e38c2.png)

**Comment by ddorstijn** [comment]
Ow and soory for the ground you can't see. But you already knew :-p

**Comment by jareiko** [comment]
Haha, I like it! I will probably add something like that. :smiley:

**Comment by jareiko** [comment]
Done!
