### ISSUE TITLE
Editor Bug

### ISSUE THREAD

**Issue by copiousopioids** [CodeArtemis/TriggerRally#28]
I don't know if this is temporary or not, but I can't edit anything in the editor. I try to move/delete/edit an object and it doesn't go anywhere. I can still drive it though.

**Comment by jareiko** [comment]
It's working for me. Are you logged in? Login sessions only seem to last a week or so at the moment, for some reason I haven't worked out yet.

**Comment by jareiko** [comment]
Oh wait, sorry, I see what you mean. The terrain doesn't update when you move checkpoints. I'll rollback the change until I can fix this.

**Comment by jareiko** [comment]
New code pushed. Bug should be fixed now, so I'm closing the bug. Please reopen if I'm wrong. :)

**Comment by copiousopioids** [comment]
Oh lol, yes it works now. Thanks! Oh, and I saw you "featured" one of my tracks. I'm flattered :laughing:
