### ISSUE TITLE
Funny sign bug

### ISSUE THREAD

**Issue by copiousopioids** [CodeArtemis/TriggerRally#29]
Umm, not sure if I want to report this because it's kind of fun. :laughing: 

When I run into a certain sign on a track, it will send me flying. 

This track: http://triggerrally.com/x/gmbnGQEQ/ArbusuG/drive

It's the chevron farthest down the road on your right. I've attached a picture of the car 
![plane](https://f.cloud.github.com/assets/2965376/62399/cbcabce8-5d0a-11e2-833e-0aeff58502cb.png)
miraculously turning into a plane. More like a crashing plane with no engine and no wings. XD

**Comment by jareiko** [comment]
Woah! :)

Since the chevrons are scaled up to max, I'm guessing this is probably a bug with collision detection for scaled objects. I'll look into it.

**Comment by copiousopioids** [comment]
Ah well, I'll have fun with it until then.
![plane2](https://f.cloud.github.com/assets/2965376/64548/6ebd6bf4-5e4f-11e2-95a2-c533bbd4c90d.png)
It started to enter a black void and I got bored.
Another time, either I ran into the cloud texture or it restarted the car.
![clouds](https://f.cloud.github.com/assets/2965376/64555/b181b7ec-5e4f-11e2-8970-284303ceb6be.png)
^^ I did eventually hit the ground on this one...but then I bounced. :laughing:

**Comment by jareiko** [comment]
Trigger Rally actually started out life as a flight simulator! Maybe one day I'll bring that code back in. :airplane:

**Comment by copiousopioids** [comment]
Seriously? I was wondering why there was a line of code that sets the vehicle as a car ("type=car"). I tried changing it to plane once and it didn't change anything. :frowning:

**Comment by jareiko** [comment]
I'm very sorry to tell you that this bug is now fixed. :wink:
