### ISSUE TITLE
Arbusu RWX-TSI

### ISSUE THREAD

**Issue by wrencherd** [CodeArtemis/TriggerRally#31]
Thanks for including the Arbusu RWX.

I have always wanted to drive one, but my dogs insisted I get the Ackabout instead.

Still an Arbusu, but not quite as much fun to drive.

**Comment by jareiko** [comment]
Thank you, this comment just made my day. :smile:

**Comment by Drvanon** [comment]
I've no idea where you are talking about!?1?!? Explanation?

**Comment by jareiko** [comment]
Arbusu is an anagram of the name of a car manufacturer. Spot the other anagrams in @wrencherd's post. :wink:

**Comment by wrencherd** [comment]
"Dogs", by the way, is not an anagram though my own often seem to believe that it might be.
