### ISSUE TITLE
Transparent ground texture with AMD Catalyst drivers on Linux

### ISSUE THREAD

**Issue by krasnoglaz** [CodeArtemis/TriggerRally#34]
Ubuntu 12.04, Catalyst 12.10, latest Chrome and Firefox browsers. Radeon 7950

Ground texture is completely invisible on non Arbusu tracks. Works fine on windows.

I know it's a driver bug, not a trigger rally one. I've just posted it for completeness.

**Comment by jareiko** [comment]
Cool, thanks for reporting this. I suspect lack of vertex texturing support is the culprit.

If you can, to confirm this please could you paste the results from this page?

http://renderingpipeline.com/webgl-extension-viewer/

**Comment by krasnoglaz** [comment]
Your WebGL implementation:

Renderer: WebKit WebGL
Vendor: WebKit
WebGL version: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL version: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Supported WebGL extensions:

OES_texture_float
OES_standard_derivatives
WEBKIT_EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
WEBKIT_WEBGL_lose_context
WEBKIT_WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_depth_texture
Implementation dependent limits:

WebGL constant  minimum maximum on your browser
MAX_COMBINED_TEXTURE_IMAGE_UNITS    8   32
MAX_CUBE_MAP_TEXTURE_SIZE   16  16384
MAX_FRAGMENT_UNIFORM_VECTORS    16  256
MAX_RENDERBUFFER_SIZE   1   16384
MAX_TEXTURE_IMAGE_UNITS 8   32
MAX_TEXTURE_SIZE    64  16384
MAX_VARYING_VECTORS 8   32
MAX_VERTEX_ATTRIBS  8   29
MAX_VERTEX_TEXTURE_IMAGE_UNITS  0   32
MAX_VERTEX_UNIFORM_VECTORS  128 256
MAX_VIEWPORT_DIMS   see specs   (16384, 16384)
NUM_COMPRESSED_TEXTURE_FORMATS  0   null

**Comment by jareiko** [comment]
Oh, you have 32 vertex texture units, so that can't be the problem. Maybe it is a driver bug, as you said.

If anyone else sees this problem please post your browser and GPU info on this thread.

**Comment by krasnoglaz** [comment]
I've just installed yesterday's Catalyst 13.1 (which I didn't know existed at the time of filing this issue) drivers. And now I can see the ground perfectly well.

**Comment by jareiko** [comment]
Good! Thanks again for the report. Others may find this useful.

**Comment by Drvanon** [comment]
you use ubuntu :+1: :+1: . but not 12.10 :-1: :-1: :-1:  Why are you doing this to me!!!!!!!!!!!
