### ISSUE TITLE
question about editing published track

### ISSUE THREAD

**Issue by wrencherd** [CodeArtemis/TriggerRally#35]
This is probably a simple question, but how do I use the "copy" function to edit a published track while leaving the "current" version still published?

Is it as simple as a name change for the "new" track?

Thanks for any help.

**Comment by jareiko** [comment]
When you copy a track, the new copy will have " copy" appended to the name, and will not be published by default even if the original was. You can make changes to it, change the name if you want, and then publish that one as well. Both will then be published and visible. Does that answer your question?

Names do not have to be unique so you could even give them the same name if you want, though that might be confusing.

**Comment by wrencherd** [comment]
Yes, it does answer the question.

Thank you.
