### ISSUE TITLE
Another enchantment

### ISSUE THREAD

**Issue by Drvanon** [CodeArtemis/TriggerRally#37]
again 3 things(sorry for my worse english)
1. And the most important one. BETTER FIRST PERSON LOOKING!!!! Sorry for that. I like firdt person really much and it's frustating to discover every time you press c you are looking as if you lay down on the car.
2. The arrow for the checkpoints dissapear when you upside down or for a big mountain. It may be possible that the arrow is in 3d too so it dissapears.
3. numbers at the speedometer. It makes more sense to me when I see how hard i'm kind of driving. And the top speed of the car :smile:

**Comment by jareiko** [comment]
1. Okay, I'll add an option to not see the car at all in 1st person mode.
2. Oh yes, hadn't noticed that! It is indeed because the arrows are 3D. Should be easy to fix.
3. It's on my to-do list, but I can't say for sure when it will be done.

**Comment by jareiko** [comment]
1. Done. There's a new inside camera mode where the car is invisible.
2. Fixed.
3. Not yet done, but this was already mentioned in another issue so I'll close this one now.
