### ISSUE TITLE
sound

### ISSUE THREAD

**Issue by ddorstijn** [CodeArtemis/TriggerRally#39]
Eh, is there a way to adjust the volume???

**Comment by jareiko** [comment]
Not at the moment, no. When I add a way to set user preferences (eg
graphics quality) I will include sound volume as an option.

**Comment by ddorstijn** [comment]
When comes that update en is it possible to just mute the sound??

**Comment by jareiko** [comment]
Just added a mute option: you can turn off audio on your user page (click the "Edit profile" button or use the link at the bottom of a Drive page.)

**Comment by jareiko** [comment]
Volume control added.
