### ISSUE TITLE
typo in car sounds

### ISSUE THREAD

**Issue by jeromeetienne** [CodeArtemis/TriggerRally#4]
looking at your sounds and found this typo in https://github.com/jareiko/TriggerRallyOE/blob/master/src/car.js#L97

```
this.sourceWind.playbackRate = windRate + 0.5;
```

i think it lt should be

```
this.sourceWind.playbackRate.value = windRate + 0.5;
```

thanks again for the links :)

**Comment by jareiko** [comment]
Oops! Thank you. :)
- Jasmine

On Thu, Jul 19, 2012 at 3:22 PM, Jerome Etienne <
reply@reply.github.com
