### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by ddorstijn** [CodeArtemis/TriggerRally#40]
Myu mind got some great ideas again.
1. What do you think of different gamemodes? Do you know dirt 3? Like a rally cross or with the big trucks or buggies? Or maybe (it is multiplayer) one is the police and one the thief and  
   the police have to arrest the other player. Car problem would be almost solved then i thinlk?
2. When you are by the last checkpoint the little transparent arrow doesn't change. wouldn't it be logistic to have just one arrow then and if you are done the track the arrow dissapears too?
3. A simple way to currently mute the sound(just until the menu comes out)? like 'm' or something?

**Comment by jareiko** [comment]
1. Haha, I like the police and thief idea! Not sure how much work that would be though.
2. Just pushed a fix for that.
3. So the sound is a problem for you? Maybe I can do something temporary, yes.

**Comment by jareiko** [comment]
Mute sound option pushed - #39. Since item (1) is not likely to be implemented soon, I'll close this issue.
