### ISSUE TITLE
Graphics quality settings

### ISSUE THREAD

**Issue by mpk** [CodeArtemis/TriggerRally#42]
I have one small suggestion for this awesome game - could you add a checkbox for enabling/disabling shadows? I think that would greatly improve performance on underpowered machines, like Ultrabooks with integrated Intel GPU - in my own Three.js experiments, disabling shadows improved frame rate from around 20 to smooth 60 FPS. 

Thanks!

**Comment by jareiko** [comment]
Graphics settings are in the works. I hadn't thought of adding a shadow option, but I'll do that. Thanks for the suggestion! :smiley:

**Comment by jareiko** [comment]
I added the option to turn off shadows. You can find it on your user page: click "Edit profile" or use the link at the bottom of a Drive page.

Unfortunately it requires you to log in to the site at the moment to persist the settings. I would like to add support for "guest users" tied to browser sessions at some point, which would make that requirement less of a problem.

It would be great if you could let me know how the shadow option affects performance on your machine! A reduced-detail terrain option is also coming soon.

**Comment by mpk** [comment]
That was really quick, thanks!

I checked it out - with shadows turned on, it runs ~7 FPS (unplayable), without shadows about 15 FPS, which is still not ideal, but at least playable. Regarding performance, I also looked at Activity Monitor, CPU usage was about 10%, so maybe the game is GPU bound in some way (it's an Intel HD3000).

By the way, wouldn't it make more sense to store graphics settings in window.localStorage? This kind of settings, I think, should be linked to browser, not account (If I switch between fast desktop and slow notebook, I will have to change settings every time) and it wouldn't require me to log in.

**Comment by jareiko** [comment]
I just added a terrain quality option, which cuts the terrain down to about 1/5 the number of triangles. Does that help the FPS?

Yup, I agree that localStorage or similar would be better. I just had the infrastructure in place for storing user data already, so it was the easiest path for now. I'll soon need to start using localStorage anyway, and at that point I'll switch it over.

**Comment by mpk** [comment]
Now it runs about 25 FPS with disabled shadows and low quality terrain :) However, the frame rate is quite unstable, but that might be Chrome / Mac OS problem.
