### ISSUE TITLE
Asking players

### ISSUE THREAD

**Issue by ddorstijn** [CodeArtemis/TriggerRally#44]
Hey, little question here. If you are so bad at modeling why don't you ask the players for help. It's a shame i can't help you because i am just 15 years old and aldo i know blender well i suck at modeling without rage quiting. I know only C, Ruby, Python and GML. So with coding of webgl i Cant help. :-( :-\

And now another enchantment:
- What do you think of manual engaging(DONT NOW IF THIS IS THE RIGHT WORD! You know put de gear in 1,2,3,4,5 and R for riding backward)

**Comment by jareiko** [comment]
I'm open to offers of help, but I would like to raise the quality level of the art assets, and that probably means getting professional work done.

Manual shifting would be cool, but most people don't care about it so it's not a priority for me right now. It will make it in eventually.
