### ISSUE TITLE
"R" button doesn't work in Chrome in fullscreen.

### ISSUE THREAD

**Issue by krasnoglaz** [CodeArtemis/TriggerRally#49]
Can't restart a race while in fullscreen using latest Google Chrome browser. Checked on windows and linux.

**Comment by jareiko** [comment]
This is an unfortunate limitation of Chrome's fullscreen implementation, for security reasons. You can only access a few keys (arrows, maybe the space bar?).

They seem to be in no hurry to change this or support the requestFullScreenWithKeys method, so I'm working on a new version of Trigger Rally which runs in the full client area of the browser at all times. If you enter Full Screen or Presentation mode manually (from the View menu) then the key restriction does not apply.

See also #5.

**Comment by mpk** [comment]
If you want to use fullscreen with keys in Chrome, you can use

```
el.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT);
```

This seems to work for me.

**Comment by jareiko** [comment]
Thanks @mpk! That worked, and I've pushed it now since it's a very small change.
