### ISSUE TITLE
Pressing C to change camera view in fullscreen doesn't work.

### ISSUE THREAD

**Issue by parkerlreed** [CodeArtemis/TriggerRally#5]
Keep up the great work! :D

**Comment by jareiko** [comment]
Works in Firefox.

Chrome has not yet implemented the requestFullScreenWithKeys method.

**Comment by parkerlreed** [comment]
Ahh ok. Now I know who to be mad at. XD Just kidding. Thanks for the great
work.

**Comment by jareiko** [comment]
Fixed for a while now.
