### ISSUE TITLE
Copy locking Tracks

### ISSUE THREAD

**Issue by MrXXX** [CodeArtemis/TriggerRally#51]
I would appreciate it if it would be possible to prevent other users copying tracks and just publishing it as theirs, without altering it in the slightest way, it's a little irritating when you spend a long time making a track and tweaking it to be right for someone to come along and steal your track and publish it as there own.

**Comment by jareiko** [comment]
That's a good idea, and it won't be too hard to implement. I'm in the middle of some deep code changes right now though, so it will probably take a week or two before I can get around to this.

I'm sorry to hear that people are abusing track copying like this. :(

**Comment by MrXXX** [comment]
thanks, i hope it's not too much trouble

**Comment by jareiko** [comment]
Don't worry, if it was too much trouble I wouldn't do it. ;) Suggestions like this are extremely welcome, thank you! I just need to find the right place for it in my to-do list. At the moment that looks like a couple of weeks from now.

**Comment by jareiko** [comment]
Done.
