### ISSUE TITLE
Just one question...

### ISSUE THREAD

**Issue by copiousopioids** [CodeArtemis/TriggerRally#54]
Why is there a Nyan cat in the Trigger Rally Code?
![nyan](https://f.cloud.github.com/assets/2965376/367404/84872fe6-a2a7-11e2-9f28-5cf9276c8ab6.gif)

:D

**Comment by joshschmille** [comment]
That's a node_module example file, I assume.

**Comment by jareiko** [comment]
Haha, good find! That reminds me though, I should remove node_modules from the repo and just leave package.json.

**Comment by jareiko** [comment]
Done.
