### ISSUE TITLE
Failure for terrain to render

### ISSUE THREAD

**Issue by MrXXX** [CodeArtemis/TriggerRally#55]
whilst using the track editor the terrain doesnt load, instead it just is a grey surface where the ground should be with trees on it, i don't know if it's just my computer or if anyone else has had a similar problem

**Comment by jareiko** [comment]
Does it work if you reload the page? If yes, please could you try loading the page a few more times and see how often it fails?

**Comment by MrXXX** [comment]
it could have just been a glitch, but I will try  anyway

**Comment by MrXXX** [comment]
It's loaded fine this time so it must have just been a glitch

**Comment by jareiko** [comment]
I think the current version is glitching quite a lot, but I've tried to fix it for the push I'm about to do. Thanks for testing!

**Comment by jareiko** [comment]
New push should have fixed it. (Fingers crossed.) Closing the issue.
