### ISSUE TITLE
icarus

### ISSUE THREAD

**Issue by bmo123** [CodeArtemis/TriggerRally#58]
I have bought thecar SEVEN times now and it keeps REFUNDING AND TAKING CAR AWAY - .- im about to spam this and punch my pc screen

**Comment by jareiko** [comment]
Nooo, don't do it!! Thanks for reporting this. What's your user id?

You're the second person I've heard this happening to, so I will step up my effort to debug it.

**Comment by jareiko** [comment]
Okay, I think I found your user ID, and I awarded you the car directly in the database. The bug is still a bit of a mystery but I'm working on it.

**Comment by jareiko** [comment]
This should now be fixed. If anyone else sees this problem, please let me know!
