### ISSUE TITLE
Visualization issue?

### ISSUE THREAD

**Issue by reidrac** [CodeArtemis/TriggerRally#61]
I tried the game with Linux and ChromeOS (it's an ARM Chromebook) and I seem to experience visualization problems... like the trees and the car are flying in a different level over the terrain.

See: 

![screenshot 2013-12-18 at 20 57 55](https://f.cloud.github.com/assets/120189/1777571/d13baefc-6827-11e3-818d-3f08fb7cbf0c.png)

**Comment by jareiko** [comment]
Looks like the GPU may not support vertex texturing, or perhaps not enough units. If that's the case, there's nothing I can do, sorry! You can check here:

http://www.doesmybrowsersupportwebgl.com/

**Comment by reidrac** [comment]
Thanks for your reply.

Perhaps you could add a FAQ or some information about requirements.

**Comment by reidrac** [comment]
Ah! Removing shadows, high detail terrain and antialiasing seems to do the trick! Now the car isn't flying anymore :)

**Comment by jareiko** [comment]
Oh! That's surprising but very interesting to know, thank you. :)
