### ISSUE TITLE
CAN'T PICKUP COINS!!!!!!!!!!!!

### ISSUE THREAD

**Issue by Mathahc** [CodeArtemis/TriggerRally#62]
It's not letting me get coins and I want COINSSSSSSSSSSSS!!!!!!!!!!!!!!!!!!!!!!!!! :(

**Comment by jareiko** [comment]
Sorry to hear that! What's your user id?

**Comment by Mathahc** [comment]
i fix that it was just a bug
- MAGICALLY DELICIOUS HAHA*

**Comment by Mathahc** [comment]
sorry to waste your time
- MAGICALLY DELICIOUS HAHA*
