### ISSUE TITLE
Google account fails to sign in

### ISSUE THREAD

**Issue by headphones1** [CodeArtemis/TriggerRally#69]
When you try to sign in with your google account, it is rejected due to out of date code. You will be brought to a page on google stating the following; 
OpenID 2.0 for Google Accounts has gone away.
![image](https://cloud.githubusercontent.com/assets/12629705/7841530/e9a14d3e-0462-11e5-9898-1739d6dbf4a5.png)

**Comment by jareiko** [comment]
Posted a $100 bounty for this issue:

https://www.bountysource.com/issues/18148989-google-account-fails-to-sign-in

**Comment by pyk** [comment]
@jareiko are #70 already solve this bounty?

**Comment by jareiko** [comment]
Gosh, I didn't even see it. I will test it when I get a chance.

**Comment by jareiko** [comment]
Will presume this is fixed and close it now.
