### ISSUE TITLE
Car flips far too easily

### ISSUE THREAD

**Issue by alistair-broomhead** [CodeArtemis/TriggerRally#8]
Using OSX Lion with Chrome

This seems to get worse as I go round the course, until eventually any attempt at cornering results in the vehicle doing repeated barrel-rolls when you make the slightest of adjustments..

**Comment by jareiko** [comment]
Thanks for reporting! Do you know if you were using version 1 or 2?

**Comment by alistair-broomhead** [comment]
I think it was version 1, there was nothing to show that there was another version on the website :s

**Comment by copiousopioids** [comment]
It's easy to flip--Ya just have to be a better driver. :D

**Comment by Vodkacannon** [comment]
Might it be that the cars mass is set too small or is it something with its center of gravity?

**Comment by copiousopioids** [comment]
Possibly--I notice that when you do flips in the air and roll on the ground that the car is very front-heavy. I've just worked around the flipping problem by driving differently. Coasting and then hitting the handbrake works well.

**Comment by alistair-broomhead** [comment]
The issue that I was originally referring to saw the car becoming more and more sensitive to flipping as I went around the course, irrespective of speed (eventually I could be almost stationary and still do corkscrews) - I'll have another play when I have time

**Comment by copiousopioids** [comment]
Oh ok. Yeah, that does seem weird and doesn't do that for me.

**Comment by jareiko** [comment]
This sounds like a weird rare bug, and it would be nice to know the reason behind it, but I'll assume it's v1 only and close the issue for now. Please re-open it if you see it happen in v2 or later, ie in any other track than "Preview".
