### ISSUE TITLE
local stragy never run!!!

### ISSUE THREAD

**Issue by cnip** [CodeArtemis/TriggerRally#9]
i can not pay this game  when trigger on button (href="/x/Preview/Arbusu/drive"),,,seem that no data founded

**Comment by jareiko** [comment]
Sorry, I don't understand. Can you explain what you were doing and what happened in more detail?

**Comment by cnip** [comment]
thank you reply, i run the code  in windows 7 system ,when click on "drive" button ,it seems do nothing . could you give more detail about how to start?

**Comment by cnip** [comment]
when redirect to (http://localhost:80/x/Preview/Arbusu/drive) the frontpage show "Not Found"
